alias as := attach-shum-server
alias au := attach-userbot
alias ks := kill-shum-server
alias ku := kill-userbot
alias ls := list-sessions
alias r := run
alias rs := run-shum-server
alias ru := run-userbot

SHUM_SERVER_SESSION_NAME := "shum-server"
USERBOT_SESSION_NAME := "userbot"

attach-shum-server:
    tmux attach -t {{SHUM_SERVER_SESSION_NAME}}

attach-userbot:
    tmux attach -t {{USERBOT_SESSION_NAME}}

kill-shum-server:
    tmux kill-session -t {{SHUM_SERVER_SESSION_NAME}}

kill-userbot:
    tmux kill-session -t {{USERBOT_SESSION_NAME}}

list-sessions:
    tmux ls

run:
    just run-shum-server
    just run-userbot

run-shum-server:
    #!/usr/bin/env sh
    tmux new-session -d -s {{SHUM_SERVER_SESSION_NAME}}
    tmux send-keys -t {{SHUM_SERVER_SESSION_NAME}} 'just -f shum-server/justfile run' C-m

run-userbot:
    #!/usr/bin/env sh
    tmux new-session -d -s {{USERBOT_SESSION_NAME}}
    tmux send-keys -t {{USERBOT_SESSION_NAME}} 'just -f userbot/justfile run' C-m
