alias r := run

run:
    ./gradlew run

build:
    ./gradlew build

clean:
    ./gradlew clean

test:
    ./gradlew test

# Run the server in development mode with auto-reload
dev:
    ./gradlew run --continuous 
