alias t := test-unit
alias tu := test-unit

run:
    #!/usr/bin/env bash
    source venv/bin/activate

    python3 main.py

setup:
    #!/usr/bin/env bash
    rm -rf venv
    python3 -m venv venv
    source venv/bin/activate
    pip3 install -r requirements.txt

test-unit:
    #!/usr/bin/env bash
    source venv/bin/activate

    python3 -m unittest discover -s tests
