alias b := build
alias r := run

build:
    ./gradlew jsBrowserDevelopmentWebpack

[working-directory: 'ts']
run: build
    npx http-server ../build/processedResources/js/main -p 8080 -o
    open http://localhost:8080

update-lock:
    ./gradlew kotlinUpgradeYarnLock
